# Generated by Django 4.1.3 on 2022-11-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Название'),
        ),
    ]
